### ISSUE TITLE
Please release a new version...

### ISSUE THREAD

**Issue by NeverGivinUp** [microsoft/DTrace-on-Windows#13]
... so we can use flamegraph-rs on Windows

**Comment by NeverGivinUp** [comment]
This https://github.com/microsoft/DTrace-on-Windows/pull/6 is the merged fix we need in the new version.

**Comment by ArthurBrussee** [comment]
I'm also running into this :/ 

I've tried compiling from source, and though after many hours of fighting VS version I can compile the project, the resulting DTrace still fails to run.

Please please actually update the version you ship.

**Comment by taviso** [comment]
I didn't try it, but guess as a workaround you could add `pid$target::RtlExitUserProcess:entry {exit(0)}`?

**Comment by haripulapaka** [comment]
Apologies everyone for radio silence, we'll work on releasing an update in the new year. cc @ashedel

**Comment by johnterickson** [comment]
@haripulapaka Any update? Thanks!

**Comment by haripulapaka** [comment]
it has been published here: https://www.microsoft.com/en-us/download/details.aspx?id=100441

cc @ashedel

**Comment by anderspedersen** [comment]
@haripulapaka 
The new version did work for some time, but for me, it already stopped working again. All the providers except for the most basic (dtrace & profile) are gone. And when trying to reinstall dtrace I get a warning that it only works on Windows version  6.3.0.0 or later. It worked perfectly two months ago, so my best guess is that an update to Windows broke dtrace.

**Comment by CodeMaxx** [comment]
Closing as v1.2 was released on 4/26/2022 as mentioned by @haripulapaka above
