### ISSUE TITLE
Add support for fds[] array

### ISSUE THREAD

**Issue by rmilkowski** [microsoft/DTrace-on-Windows#16]
It would be really nice if the fds[] array was supported as well which is handy for cases like below.

PS C:\Program Files\DTrace> .\dtrace -n syscall::NtWriteFile:entry'{trace(fds[arg0].fi_pathname);}'
dtrace: invalid probe specifier syscall::NtWriteFile:entry{trace(fds[arg0].fi_pathname);}: in action list: fds has not yet been declared or assigned

**Comment by ashedel** [comment]
These are from another world. Doubt that fds[] will ever be implemented on NTOS platform.
