### ISSUE TITLE
Support for dtrace in Windows Sandbox

### ISSUE THREAD

**Issue by zllovesuki** [microsoft/DTrace-on-Windows#17]
One of the use case for dtrace on Windows would be to better understand unknown software behavior better, under a more isolated environment. Now that you can run binaries in Sandbox, will Sandbox eventually support dtrace? Asking because you can't do `bcdedit` in Sandbox.

**Comment by CodeMaxx** [comment]
Hey @zllovesuki, you should be able to do this if you can put the bcdedit settings in the sandbox image to begin with and turn on DTrace. Then DTrace should be able to run in Sandbox.
