### ISSUE TITLE
Dtrace for older builds like 17763 for Windows Server

### ISSUE THREAD

**Issue by gonchik** [microsoft/DTrace-on-Windows#52]
Hi!

I really like that DTrace for Windows is a thing, thanks for that! 

Do you have a plan for the providing installation and work option for old releases? 

`](dtrace: failed to initialize dtrace: DTrace device not available on system)`

or do you have instruction for the building for the custom builds ?
that one did not help for old release  https://github.com/microsoft/DTrace-on-Windows/blob/windows/COMPILING.md

Cheers,
GT

**Comment by CodeMaxx** [comment]
Hey @gonchik, DTrace is only supported in the builds of Windows after version 18980 and Windows Server Build 18975.

There won't be support for older versions.

**Comment by gonchik** [comment]
Hey, @CodeMaxx , 
thanks for that info
