### ISSUE TITLE
Windows 11 support

### ISSUE THREAD

**Issue by LucasArona** [microsoft/DTrace-on-Windows#53]
Hello,

Is DTrace supposed to work on Windows 11? Only the dtrace and profile probes are shown when running on Win11. Are there any additional configuration steps to perform compared to Win10?

**Comment by gonchik** [comment]
Hello, I am also interested

**Comment by CodeMaxx** [comment]
@LucasArona @gonchik The currently released version of DTrace will not work on Windows 11. I'll look into updating it for Win11.

**Comment by gonchik** [comment]
Hi @CodeMaxx , thanks for heads up

**Comment by CodeMaxx** [comment]
@LucasArona @gonchik I have released a [new version of DTrace](https://www.microsoft.com/en-us/download/details.aspx?id=100441) on Microsoft Downloads. Please try that out and let me know if it works for you.

**Comment by gonchik** [comment]
@CodeMaxx  Thank you! I will try and come back if something wrong ;)

**Comment by LucasArona** [comment]
@CodeMaxx Yes it works on Windows 11 with this new release, thank you!
