### ISSUE TITLE
no providers after installation

### ISSUE THREAD

**Issue by ahl** [microsoft/DTrace-on-Windows#7]
I installed DTrace for Windows for the first time and I only see the `dtrace` provider in `dtrace -l`:

```
C:\Windows\system32>dtrace -l
   ID   PROVIDER            MODULE                          FUNCTION NAME
    1     dtrace                                                     BEGIN
    2     dtrace                                                     END
    3     dtrace                                                     ERROR
```

I'm a Windows neophyte so I may be doing something wrong, but I tried to follow the install instructions.

**Comment by haripulapaka** [comment]
hi Adam, i think that means there was some mismatch with the build and dtrace driver. did you use instructions from here? https://techcommunity.microsoft.com/t5/windows-kernel-internals/dtrace-on-windows-20h1-updates/ba-p/1127929

cc @ashedel @maxrenke

**Comment by ahl** [comment]
That fixed it. I was using older instructions. It looks like the link from the README.md may refer to old bits as well.

**Comment by sklaw** [comment]
I have the same issue on 20H2 build 19042.1466

**Comment by sklaw** [comment]
> I have the same issue on 20H2 build 19042.1466

Turns out I wasn't running Windows Insider... Installing Windows Insider fixed it

**Comment by CodeMaxx** [comment]
Closing as this was resolved
